/**
 * Harmonic Palette Generator — mdvdb
 *
 * Generates N harmonically-spaced colors from a base color by rotating hue
 * around the color wheel while preserving saturation and lightness.
 * Uses the golden angle (~137.5°) so consecutive indices are maximally distinct.
 * Produces visually cohesive palettes that adapt to any accent color and theme.
 */

import { hexToHsl, hslToHex, contrastRatio, relativeLuminance } from './color-utils'

/** A generated harmonic color palette */
export interface HarmonicPalette {
  /** Hex color strings, length = count. palette[0] is always the base color. */
  colors: string[]
  /** Base hue in degrees (0-360) */
  baseHue: number
  /** Effective saturation used for generation (0-100, after floor) */
  saturation: number
  /** Effective lightness used for generation (0-100, after clamping) */
  lightness: number
  /** Optional common relative-luminance target for perceptually balanced colors. */
  targetLuminance?: number
}

/** Minimum saturation floor for near-gray colors */
const MIN_SATURATION = 40

/** Lightness range clamp for palette generation */
const MIN_LIGHTNESS = 25
const MAX_LIGHTNESS = 75

/**
 * The golden angle in degrees (~137.508°).
 * Each successive color lands as far as possible from all previous colors,
 * ensuring that cluster 0, 1, 2, 3... always look visually distinct
 * regardless of how many clusters exist.
 */
const GOLDEN_ANGLE = 360 * (1 - 1 / ((1 + Math.sqrt(5)) / 2)) // ≈ 137.508°

/**
 * Generate N harmonically-spaced colors from a base hex color.
 *
 * - Colors are generated by rotating hue using the golden angle (~137.5°).
 *   This ensures consecutive indices (cluster 0, 1, 2, 3...) are maximally spread
 *   across the color wheel, unlike equal spacing where neighbors look similar.
 * - `offset` skips the first N golden-angle slots, so the palette avoids hues
 *   already used by another palette (e.g. arrow colors). Default 0.
 * - Near-gray colors (saturation < 10) get a saturation floor of 40.
 * - Extreme lightness values are clamped to 25-75 for generated colors.
 */
export function generateHarmonicPalette(
  baseHex: string,
  count: number,
  offset: number = 0
): HarmonicPalette {
  const hsl = hexToHsl(baseHex)

  const effectiveS = hsl.s < 10 ? MIN_SATURATION : hsl.s
  const effectiveL = Math.max(MIN_LIGHTNESS, Math.min(MAX_LIGHTNESS, hsl.l))

  const colors: string[] = []

  for (let i = 0; i < count; i++) {
    const hue = (hsl.h + (i + offset) * GOLDEN_ANGLE) % 360
    colors.push(hslToHex(hue, effectiveS, effectiveL))
  }

  return {
    colors,
    baseHue: hsl.h,
    saturation: effectiveS,
    lightness: effectiveL
  }
}

/**
 * Balance an existing harmonic palette to a common perceived brightness.
 *
 * Equal HSL lightness is not equal perceived brightness: saturated green can
 * be many times brighter than blue or magenta. That difference is especially
 * destructive for thousands of translucent graph edges because the brightest
 * hue wins every overlap. This keeps each color's hue, caps extreme chroma,
 * and binary-searches HSL lightness until its WCAG relative luminance is near
 * the requested target.
 */
export function balancePaletteLuminance(
  palette: HarmonicPalette,
  targetLuminance: number = 0.16,
  maxSaturation: number = 82
): HarmonicPalette {
  const target = Math.max(0.02, Math.min(0.9, targetLuminance))
  const saturationCap = Math.max(0, Math.min(100, maxSaturation))
  const colors = palette.colors.map((color) => {
    const hsl = hexToHsl(color)
    const saturation = Math.min(hsl.s, saturationCap)
    let low = 0
    let high = 100

    // Eighteen iterations are ample for an 8-bit output color while keeping
    // the result deterministic across browsers and themes.
    for (let step = 0; step < 18; step++) {
      const lightness = (low + high) / 2
      const candidate = hslToHex(hsl.h, saturation, lightness)
      if (relativeLuminance(candidate) < target) low = lightness
      else high = lightness
    }

    return hslToHex(hsl.h, saturation, (low + high) / 2)
  })

  return {
    ...palette,
    colors,
    saturation: Math.min(palette.saturation, saturationCap),
    targetLuminance: target
  }
}

/**
 * Get a single color from a harmonic palette by index.
 * Wraps via modulo for indices >= palette size.
 */
export function paletteColor(palette: HarmonicPalette, index: number): string {
  const len = palette.colors.length
  return palette.colors[((index % len) + len) % len]
}

/**
 * Get a palette color adjusted for use as text on the current background.
 * Brightens dark colors on dark backgrounds, darkens light colors on light backgrounds,
 * ensuring a minimum contrast ratio of 3:1 (WCAG AA for large text / UI elements).
 */
export function paletteTextColor(
  palette: HarmonicPalette,
  index: number,
  backgroundHex: string
): string {
  const hex = paletteColor(palette, index)
  if (contrastRatio(hex, backgroundHex) >= 3.0) return hex

  const hsl = hexToHsl(hex)
  const bgHsl = hexToHsl(backgroundHex)
  const shouldBrighten = bgHsl.l < 50

  for (let step = 0; step < 40; step++) {
    hsl.l = shouldBrighten ? Math.min(95, hsl.l + 2) : Math.max(5, hsl.l - 2)
    const candidate = hslToHex(hsl.h, hsl.s, hsl.l)
    if (contrastRatio(candidate, backgroundHex) >= 3.0) return candidate
  }
  return hslToHex(hsl.h, hsl.s, hsl.l)
}
